### ISSUE TITLE
Temporary solution / workaround which works

### ISSUE THREAD

**Issue by suskozaver** [antoinebou12/hass_renpho#21]
A hack solution to make it work, without the hass_renpho integration:

Add the following to your configuration.yaml of HA:

```
rest:
- resource: "http://renpho.qnclouds.com/api/v3/users/sign_in.json?app_id=Renpho&email=youremail%40domain.com&password=yourpassword"
  method: "POST"
  scan_interval: 3600 
  sensor:
  - name: Susko weight
    unique_id: susko_weight
    value_template: "{{ value_json.weight}}"
```

It will create a sensor and retrieve the data every hour and store it. 

This works only for the primary user.
